baseURL: https://chaman.netlify.app

languageCode: en-us
title: "Chaman"
theme: "toha"

# Allow raw html in markdown file
markup:
  goldmark:
    renderer:
      unsafe: true

# Enable Google Analytics
googleAnalytics: UA-122321624-2

# Enable Disqus forum
disqusShortname: Welcome to the World of Chaman Gupta

# Enable global emoji support
enableEmoji: true

# Custom parameters
params:
  # background image of the landing page
  background: "images/website_background.jpg"

  # GitHub repo URL of your site
  gitRepo: https://github.com/professorchaman/chaman.github.io

  # specify whether you want to write blog post or not
  enableBlogPost: true

  # specify the list of custom menus that you want to show in the top navbar.
  # they will be separated by a divider from the main menus.
  customMenus:
  - name: Notes
    url: <Need to add a link here>

  # some information about you
  author:
    name: "Chaman Gupta"
    image: "images/myAvatar.png"
    # give your some contact information. they will be used in the footer
    contactInfo:
      email: "chaman@uw.edu"
      phone: "+12063833514"
    # a summary of what you do
    summary:
    - Stay Happy
    - Stay Awesome
    - Peace is the mission
